# Various jobs that run when a new commit is pushed to the main branch.
name: Main Merge
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  # Update the release draft with the latest changes.
  update_release_draft:
    name: Update Release Draft
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
