name: Deploy Documentation
on:
  pull_request:
    branches:
      - main
  # Allow to manually run
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      # Setup Python so that Poetry can install dependencies
      - name: Setup Python
        with:
          python-version: '3.12'
        uses: actions/setup-python@v5.1.0
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build Docs
        working-directory: docs
        run: poetry run make html
      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: docs/build/html/
      - name: Deploy Documentation
        uses: actions/deploy-pages@v4.0.5
