# Various jobs that run on a Pull Request.
name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  # Check that the commit history follows Conventional Commit format.
  conventional-commit:
    name: Conventional Commit Enforcement
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit Lint
        uses: opensource-nepal/commitlint@v1.0.0
  # Run unit and end-to-end tests on a variety of different OS and Python
  # versions.
  multi-version-tests:
    name: Unit Tests on Multiple Versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        python_version: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Run Unit Tests
        run: poetry run pytest
      - name: Run End-to-End Test
        run: poetry run example-python-package 1 2
  # Run unit tests to capture code coverage reports. This is a bit redundant
  # with the previous job, but it is run here to avoid the need to merge
  # reports from each OS and Python version.
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Setup Python
        with:
          python-version: '3.12'
        uses: actions/setup-python@v5.1.0
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Run Tests
        run: poetry run pytest --cov --cov-report term --cov-report xml:coverage.xml --junit-xml=results.xml
      - name: Output Results
        uses: MishaKav/pytest-coverage-comment@v1.1.51
        with:
          junitxml-path: ./results.xml
          junitxml-title: "Test Summary"
          pytest-xml-coverage-path: ./coverage.xml
  # Run a linter to check for code style issues.
  linting:
    name: Linting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
