# Various checks that must pass prior to merging a Pull Request.
name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Run Unit Tests
        run: poetry run pytest --junitxml=test_results/unit-results.xml
      - name: Publish Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        with:
          files: |
            test_results/unit-results.xml
        
