# Various checks that must pass prior to merging a Pull Request.
name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
jobs:
  # Run unit and end-to-end tests on a variety of different OS and Python versions.
  multi-version-tests:
    name: Run Tests on Multiple Versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        python_version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Run Unit Tests
        run: poetry run pytest
      - name: Run End-to-End Test
        run: poetry run example-python-package 1 2
  # Run on a single version to extract test and coverage reports.
  # This is a bit duplicative, since it runs above as well.
  run-with-reports:
    name: Run Tests and Report
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Setup Python
        with:
          python-version: '3.12'
        uses: actions/setup-python@v5.1.0
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev
      - name: Run Tests
        run: poetry run pytest --cov --cov-report term --cov-report xml:coverage.xml --junit-xml=results.xml
      - name: Output Results
        uses: MishaKav/pytest-coverage-comment@v1.1.51
        with:
          junitxml-path: ./results.xml
          junitxml-title: "Test Summary"
          pytest-xml-coverage-path: ./coverage.xml
